name: telegram message

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on push
        uses: peter-evans/telegram-action@v1
with:
  token: ${{ secrets.TELEGRAM_TOKEN }}
  chat_id: ${{ secrets.TELEGRAM_TO }}
  message: "Test message from GitHub Actions"
