name: TEST upload to Telegram

on:
  workflow_dispatch:  # Allows manual workflow execution

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: infatest  # Checkout the infatest branch

      - name: Get latest release
        id: get_release
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.MY_TOKEN}}
          script: |
            const release = await github.rest.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            console.log(release.data);
            return release.data;

      - name: Download and rename release asset
        run: |
          asset_url=$(echo '${{ steps.get_release.outputs.result }}' | jq -r '.assets[0].browser_download_url')
          tag_name=$(echo '${{ steps.get_release.outputs.result }}' | jq -r '.tag_name')
          wget $asset_url -O "Infamick-script-${tag_name}-Magisk-TEST.zip"

      - name: Notify Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          document: Infamick-script-${{ fromJson(steps.get_release.outputs.result).tag_name }}-Magisk-TEST.zip
          format: markdown
          disable_web_page_preview: true
          message: |
            *TEST: New Infamick Script ${{ fromJson(steps.get_release.outputs.result).tag_name }} MAGISK Update...! 🎉*    
            
            *CHANGELOG:*
            ```
            ${{ fromJson(steps.get_release.outputs.result).body }}
            ```
            
            *Repository:* [${{ github.repository }} (infatest branch)](https://github.com/${{ github.repository }}/tree/infatest)
            
            *Commit SHA:* [Click here](https://github.com/${{ github.repository }}/commit/${{github.sha}})
            
            *Installation :* [Click here](https://github.com/Infamousmick/Infamick-script/blob/infatest/README.md#installation)

            *USAGE:*
            Enter terminal with root and run
            ```
            infamick command
            ```

            *Available commands:*
            ```
            infamick battery
            ```
            Display battery health and charging cycles
            ```
            infamick boosta
            ```
            Boost Apps performances
            ```
            infamick boostb
            ```
            Improves Battery draining
            ```
            infamick boot
            ```
            Reset boot count settings
            ```
            infamick cache
            ```
            Trim cache multiple times
            ```
            infamick gmsd
            ```
            Disable GMS services
            ```
            infamick gmse
            ```
            Enable GMS services
            ```
            infamick info
            ```
            Show help and usage information
            ```
            infamick sot
            ```
            Calculate the SOT with 100% battery
            ```
            infamick temp
            ```
            Monitor system temperatures

            *⚠️ THIS IS A TEST VERSION ⚠️*

            [Join Telegram Channel](https://t.me/your_channel_name)