name: Upload to Telegram

on:
  workflow_dispatch:  # Allows manual workflow execution

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get latest release
        id: get_release
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.MY_TOKEN}}
          script: |
            const release = await github.rest.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            console.log(release.data);
            return release.data;

      - name: Download and rename release asset
        run: |
          asset_url=$(echo '${{ steps.get_release.outputs.result }}' | jq -r '.assets[0].browser_download_url')
          tag_name=$(echo '${{ steps.get_release.outputs.result }}' | jq -r '.tag_name')
          wget $asset_url -O "Infamick-script-${tag_name}-Magisk.zip"

      - name: Notify Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          document: Infamick-script-${{ fromJson(steps.get_release.outputs.result).tag_name }}-Magisk.zip
          format: html
          disable_web_page_preview: true
          message: |
            <b>New Infamick Script ${{ fromJson(steps.get_release.outputs.result).tag_name }} MAGISK Update...! 🎉</b>                   
            <b>Repository:</b> <a href="https://github.com/${{ github.repository }}">${{ github.repository }}</a>
            
            <b>Commit SHA:</b> <a href="https://github.com/${{ github.repository }}/commit/${{github.sha}}">Click here</a>
            
            <b>Installation :</b> <a href="https://github.com/Infamousmick/Infamick-script?tab=readme-ov-file#installation">Click here</a>

            <b>Download:</b> Download latest zip release <a href="https://github.com/${{ github.repository }}/releases/latest">here</a>

            <b>USAGE:</b>
            Enter terminal with root and run
            <pre><code>infamick command</code></pre>

            <b>Available commands:</b>
            <pre><code>infamick battery</code></pre>
            Display battery health and charging cycles
            <pre><code>infamick boosta</code></pre>
            Boost Apps performances
            <pre><code>infamick boostb</code></pre>
            Improves Battery draining
            <pre><code>infamick boot</code></pre>
            Reset boot count settings
            <pre><code>infamick cache</code></pre>
            Trim cache multiple times
            <pre><code>infamick gmsd</code></pre>
            Disable GMS services
            <pre><code>infamick gmse</code></pre>
            Enable GMS services
            <pre><code>infamick info</code></pre>
            Show help and usage information
            <pre><code>infamick sot</code></pre>
            Calculate the SOT with 100% battery
            <pre><code>infamick temp</code></pre>
            Monitor system temperatures
