name: Notify Telegram

on:
  workflow_dispatch:  # Permette l'esecuzione manuale del workflow

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Notify Telegram
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d text="Un nuovo messaggio inviato manualmente dal workflow GitHub Actions!"
