name: Notify Telegram

on:
  workflow_dispatch:  # Permette l'esecuzione manuale del workflow

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            *${{ github.actor }} created commit:*
            _Commit message:_ ${{ github.event.commits[0].message }}

            _Repository:_ ${{ github.repository }}

            _See changes:_ [Link](https://github.com/${{ github.repository }}/commit/${{ github.sha }})
          parse_mode: markdownV2
