name: Release Changelog to Telegram

on:
  release:
    types: [published]

jobs:
  notify-telegram:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get release info
      id: release
      uses: actions/github-script@v3
      with:
        script: |
          const release = context.payload.release;
          return { name: release.name, body: release.body };

    - name: Send message to Telegram
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        RELEASE_NAME: ${{ steps.release.outputs.name }}
        RELEASE_BODY: ${{ steps.release.outputs.body }}
      run: |
        curl -s -X POST https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage \
          -d chat_id=$TELEGRAM_CHAT_ID \
          -d text="New release: *$RELEASE_NAME*%0A%0A$RELEASE_BODY" \
          -d parse_mode=Markdown
