name: Upload Test Release

on:
  workflow_dispatch:  # Allows manual workflow execution

jobs:
  upload_and_notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get version from update.json
        id: get_version
        run: |
          VERSION=$(jq -r .version update.json)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Set changelog
        id: set_changelog
        run: |
          echo "CHANGELOG<<EOF" >> $GITHUB_OUTPUT
          echo "## ${{ steps.get_version.outputs.VERSION }} - Samsung Tweaks (July 26, 2024)
          - Added Samsung Tweaks
            1. CSC changer
              - Change current CSC
            2. Deknoxer
              - Disable or Enable knox packages
            3. Extra Dim
              - Open hidden Extra Dim menu
            4. Gesture
             - Open hidden Gestures menu
            5. Change Network Bands
             - Open 5G Network Bands guide
            6. Lock Network Bands
             - Open Network Bands settings" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create and push tag
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag -a "Test-${{ steps.get_version.outputs.VERSION }}" -m "Test release ${{ steps.get_version.outputs.VERSION }}"
          git push origin "Test-${{ steps.get_version.outputs.VERSION }}"

      - name: Create Magisk ZIP file
        run: |
          zip -r Infamick-script-${{ steps.get_version.outputs.VERSION }}_MAGISK_TEST.zip \
          changelog.md common customize.sh infamick META-INF module.prop README.md uninstall.sh

      - name: Create Test Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: Test-${{ steps.get_version.outputs.VERSION }}
          release_name: Test Release ${{ steps.get_version.outputs.VERSION }}
          body: ${{ steps.set_changelog.outputs.CHANGELOG }}
          draft: false
          prerelease: true

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Infamick-script-${{ steps.get_version.outputs.VERSION }}_MAGISK_TEST.zip
          asset_name: Infamick-script-${{ steps.get_version.outputs.VERSION }}_MAGISK_TEST.zip
          asset_content_type: application/zip
